import 'dotenv/config';
import mongoose from 'mongoose';
import Entry from '../src/models/Entry.js';

const entries = [
  {title:'Eldan Elias',category:'Characters',summary:'Protagonist. Near-future Pennsylvania carpenter and avid gamer, unwitting Vurdaal agent.',body:'Lives in Adams County near Gettysburg in a small house in a valley with his wife and children. Privately motivated, hands-on, athletically gifted, family-first. Possesses extraordinarily rare and powerful magical potential hidden from both him and the reader for much of the story. Believes he is beta-testing an advanced holodeck-like gaming experience. Eventually captured by Kol Emet, learns the truth, becomes a double agent to protect his family. Name is an anagram of Daniel (author). Elias chosen for its Hebrew meaning and allegorical resonance.',tags:['Eldan','Protagonist','Vurdaal','KolEmet','Earth'],open_question:''},
  {title:'Ruth Elias',category:'Characters',summary:"Eldan's wife. Bubbly, warm, patient, blunt, strawberry blonde with wavy hair.",body:"Ruth is Eldan's anchor in the human sense — grounded, perceptive, and deeply relational. Her behavior under fear and pressure is an open question to be developed. Strawberry blonde, wavy hair.",tags:['Ruth','Protagonist','Earth'],open_question:"How does Ruth behave under fear and pressure?"},
  {title:'Zhalek Xitren',category:'Characters',summary:'Creator of the World Train. A Xorlek genius from the planet Xor. Lost from his home network.',body:'A Xorlek male of dark blue hue with thick, short, black curly hair (fluffy mop, 2-3" with curls). Skin and hair carry deep purple bioluminescence in lightning-like patterns; roughly 5% of his hair strands are fully lit single strands. Four arms (second pair below first at the shoulder joint). Seven fingers per hand. Three pairs of antennae: above forehead, top-back, and straight back. Slightly flattened nose, pointed elf-like ears. Adult male Xorlek average 7\' to 8\'4" tall. Meticulous academic record-keeper. Discovered the soft spot between Xor and a neighboring world, developed the four-dimensional vector theory of world-crossing, and built the World Train. On his first self-test the anchor mechanism was sabotaged (likely by demonic forces on Xor) and he was unable to return home. He continued his work on a new network, eventually becoming the founder of what grew into the Kol Emet network. Whether he ever returned to Xor is unresolved.',tags:['Zhalek','Xor','Xorlek','WorldTrain','Founder','KolEmet'],open_question:'Does Zhalek ever return to Xor? Who on Xor discovered his writings and when? Did anyone on Xor know what he was working on?'},
  {title:'Xor',category:'Worlds',summary:'Home world of the Xorlek people and birthplace of the World Train.',body:"A world of highly magical and intellectually gifted beings. Architecture evokes the scale and elegance of Stargate Atlantis — organic, ancient, and built for beings of great stature. The Xorlek are humanoid with four arms, seven fingers per hand, three pairs of antennae, bioluminescent skin in blues, greens, and purples, slightly translucent. Adults average 7'-8'4\" (male) and roughly 6\" shorter (female). Slightly flattened noses, pointed elf-like ears. Xor is named for what the Xorlek call themselves. Xor sits on an isolated network, currently disconnected from the Kol Emet network. A future book will explore the angelic reconnection of these two networks.",tags:['Xor','Xorlek','WorldTrain','Founder'],open_question:"When and how does the Xor network reconnect with the Kol Emet network? Is Zhalek's original base of operations on Xor still known?"},
  {title:'Adamah',category:'Worlds',summary:'Home world of the Da Emetim people and founding world of Kol Emet.',body:'Named from the Hebrew word for earth/ground (Genesis 1). The name carries connotations of rootedness, foundation, and the stuff of creation — contrasting with the shapeshifter Vurdaal homeworld whose people have no fixed form. Kol Emet is still based here. The Da Emetim physical appearance is not yet fully developed.',tags:['Adamah','DaEmetim','KolEmet'],open_question:"What do the Da Emetim look like? What made Adamah marginally more responsive to God's call than other worlds?"},
  {title:'Kol Emet',category:'Organizations',summary:'The main good-guy organization. Hebrew: Voice of Truth. Founded by Da Emetim of Adamah.',body:"Kol Emet means Voice of Truth in Hebrew. Named from the Da Emetim people (Knowers of Truth) who founded it. Operates the largest known World Train network, which includes Earth. Works to responsibly steward knowledge of the World Train, protect worlds not ready for it, and counteract the Vurdaal. Uses human and non-angelic agents because angels are anchored to their home worlds and cannot operate freely elsewhere. Kol Emet knows the theory of how the World Train works at a foundational level, inherited from Zhalek's writings on the network he created after being stranded.",tags:['KolEmet','DaEmetim','Adamah','WorldTrain'],open_question:"Does Kol Emet know that Zhalek's secondary base of operations exists on their network? Do they know the full origin story of the Train?"},
  {title:'The Vurdaal',category:'Organizations',summary:'The main antagonist organization. Demonic in origin. Uses shapeshifter agents from their home world.',body:"Likely created or inspired by Satan and/or fallen angelic forces once the World Train was established, as a direct counter to the apologetic power the Train poses to Satan's cause. Their home world is populated by shapeshifters — beings who can naturally change their appearance — making them ideal infiltrators of other worlds. Their home world people have no innate magic but use magi-tech devices to operate the World Train and create anchors. The Vurdaal works to suppress cross-world recognition of the incarnate Christ figures, control World Train access, and keep certain worlds isolated. Anchor warfare (destroying or stealing anchors) is a known Vurdaal tactic.",tags:['Vurdaal','Shapeshifters','WorldTrain','Satan'],open_question:"What is the name of the Vurdaal home world and their people? Exactly how and when was the Vurdaal founded?"},
  {title:'Da Emetim',category:'Characters',summary:'The people of Adamah. Founders of Kol Emet. Humanoid. Name means Knowers of Truth.',body:"Da Emetim (plural; singular: Da Emeti) derives from Hebrew roots: Da (knowledge/knowing, from yada) + Emet (truth). Pronounced: Dah Eh-meh-TEEM. Humanoid. Physical appearance not yet fully developed. Grounded and unchanging in nature — a deliberate contrast to the shapeshifter Vurdaal people. Their name gave rise to the organization name Kol Emet (Voice of Truth). All communication in-world is treated as English for narrative purposes; magical translation is a possible in-world explanation.",tags:['DaEmetim','Adamah','KolEmet'],open_question:'What do the Da Emetim look like physically?'},
  {title:'World Train mechanics',category:'Lore & Mechanics',summary:'How the World Train works. Four-dimensional vector travel along the grain of world-crossings.',body:"Worlds exist in four-dimensional space. Each crossing point between worlds has a directional grain — a natural soft spot with a specific vector orientation. Zhalek discovered the first such soft spot between Xor and a neighboring world. Crossing requires following this grain precisely using a straight section of track. A train (rather than any other vehicle) is necessary because travel commits you to following a fixed path — the rails ARE the mechanism for aligning with the four-dimensional grain. A curved track introduces angular deviation and causes the crossing to fail or deposit the traveler in an unintended world. The spell/magic selects a vector direction and magnitude in 4D space. An anchor stores the precise vector needed to return to a specific world — without one, returning requires perfect recall of the exact vector, which is practically impossible. Magi-tech devices allow non-magical beings to cast the crossing spell but the user still manually selects the vector — devices do not auto-calculate it.",tags:['WorldTrain','Mechanics','Anchor','Magic','Zhalek'],open_question:''},
  {title:'Anchor system',category:'Lore & Mechanics',summary:'Magical stored vectors that allow reliable return to a specific world.',body:"An anchor is a stored four-dimensional vector — the exact orientation and magnitude of the path back to a specific world. Without an anchor, a traveler must perfectly recall and reverse their original vector to return, which is effectively impossible given the precision required. Losing or destroying an anchor is catastrophic unless another person still holds an anchor to that world and can help recreate it. Anchor warfare — destroying an enemy's anchors — is a known Vurdaal tactic. As long as one person on a network still holds an anchor to a given world, that world can be reconnected. Angelic beings (except Satan and Michael) are themselves anchored to their home worlds, losing power the longer they stay away — a parallel to the physical anchor mechanic.",tags:['Anchor','WorldTrain','Mechanics','Vurdaal'],open_question:'Can anchors be copied or forged? What exactly happens to a traveler between worlds if their anchor is destroyed mid-journey?'},
  {title:'Spiritual warfare framework',category:'Lore & Mechanics',summary:'How angelic and demonic forces operate across worlds. Jurisdictional, anchored, finite in some senses.',body:"God created all worlds simultaneously. Angelic beings were created at the same time and assigned jurisdictional stewardship over individual worlds (cf. Deuteronomy 32:8, Daniel 10 Prince of Persia model). There is one Satan — not a separate fallen being per world. Satan took a third of angels in his rebellion; those fallen angels are likewise distributed across worlds by jurisdiction. Satan and Michael alone have God-granted free travel across all worlds without anchor limitation. All other angels lose power the longer they remain away from their home world — they ARE anchored, mirroring the physical travel mechanic. This means both Kol Emet and the Vurdaal rely on non-angelic mortal agents for sustained cross-world operations. The World Train's creation forced both sides to adapt their strategies. Reconnecting isolated networks is a major spiritual battle — both sides contest any such reconnection.",tags:['Angels','Satan','Michael','Theology','Mechanics','WorldTrain'],open_question:'Does Satan know about every World Train network? How does Michael coordinate with Kol Emet?'},
  {title:'Incarnation across worlds',category:'Lore & Mechanics',summary:'Every world has its own incarnate Christ figure. Central theological pillar of the series.',body:"God the Son came incarnate into each world as an atoning figure. Each incarnation is world-specific — different names, histories, cultures — but the same truth. This is the foundational theological premise, influenced by but not derivative of C.S. Lewis. The cross-world apologetic problem: one would expect that as soon as travelers compare notes across worlds, the parallel incarnations would be overwhelming evidence. Countermeasures: (1) by the time of comparison, incarnation accounts are heavily mythologized and hard to recognize across cultural translation; (2) human motivated unbelief (Romans 1) — people actively suppress truth; (3) the Vurdaal specifically works to prevent cross-world recognition of this pattern. Two worlds with a natural bridge/soft spot between them complicate this further — the bridge was unknown/sealed, and Zhalek opened it.",tags:['Theology','Incarnation','Vurdaal','KolEmet'],open_question:'How do two worlds with a long-standing soft spot between them handle having two separate incarnations without cross-contamination of knowledge?'},
  {title:'Network topology',category:'Lore & Mechanics',summary:'How World Train networks form, connect, and isolate. Web structure, not universal connection.',body:"The World Train does not instantly connect all worlds. Each journey physically establishes a link between two worlds via anchor. Networks grow as a web — each new journey extends the graph. Isolated networks can form if all anchors between two network clusters are lost; reconnection probability is infinitesimally small without intervention. Only angelic forces (contesting each other) can reliably bridge isolated networks. The Kol Emet network is the largest known network and includes Earth. The Xor network is currently isolated from the Kol Emet network. A future book will depict angelic forces bridging these two networks. Multiple fully isolated networks likely exist across infinite worlds. Side stories can be set on isolated networks without affecting main continuity.",tags:['WorldTrain','Mechanics','Networks','KolEmet','Xor'],open_question:'How many isolated networks exist of significant size? Which networks does the Vurdaal control or heavily influence?'},
  {title:'Setting — near-future Earth (c. 2041)',category:'Worlds',summary:"Eldan's home world. Adams County, Pennsylvania. AI and robotics displacement already underway.",body:"Set around 2041. AI and robotics displacement is a functioning reality, serving as allegorical backdrop mirroring the theme of worlds not being ready for power. Eldan lives near Gettysburg in a small house in a valley with Ruth and their children. He is a carpenter — a hands-on trade in a world of increasing automation.",tags:['Earth','Eldan','Setting'],open_question:''},
  {title:'Open Q — Ruth under pressure',category:'Open Questions',summary:'How does Ruth behave when afraid or under extreme stress?',body:"Left open from an earlier session. Ruth is established as bubbly, warm, patient, and blunt in normal circumstances. Her character under fear, pressure, or crisis has not yet been developed. This will affect how she responds when she learns the truth about Eldan's situation.",tags:['Ruth','Character'],open_question:''},
  {title:"Open Q — Zhalek's home on the Kol Emet network",category:'Open Questions',summary:'Where did Zhalek settle after being stranded? Does Kol Emet know this world?',body:"Zhalek built a new base of operations on whatever world he landed on after being stranded. That world is somewhere on the Kol Emet network. Does Kol Emet know about it? Do they know it is the secondary origin point of the World Train? Is there a world on the Kol Emet network that is culturally aware of being Zhalek's adopted home? Could this be a meaningful location in the main story or a side story?",tags:['Zhalek','KolEmet','WorldTrain','Founder'],open_question:''},
  {title:'Open Q — Vurdaal home world name and people',category:'Open Questions',summary:'The shapeshifter home world and its people need names.',body:"The Vurdaal are based on a world of natural shapeshifters who use magi-tech rather than innate magic. The world and its people need names. The shapeshifter nature of the people is thematically tied to deception and corruption — a people whose very nature is to be something other than what they are.",tags:['Vurdaal','Shapeshifters'],open_question:''},
  {title:'Open Q — Da Emetim physical appearance',category:'Open Questions',summary:'What do the Da Emetim look like? Daniel has vague ideas forming.',body:'Da Emetim are humanoid but not yet visually designed. Daniel has vague ideas forming. To be developed in a future session.',tags:['DaEmetim','Adamah','KolEmet'],open_question:''},
];

await mongoose.connect(process.env.MONGO_URI);
console.log('Connected to MongoDB');

await Entry.deleteMany({});
console.log('Cleared existing entries');

const inserted = await Entry.insertMany(entries);
console.log(`Seeded ${inserted.length} entries`);

await mongoose.disconnect();
